import { useEffect, useState } from "react";
import { ArrowDown, ArrowUpRight, Check, Menu, Moon, Sun, X } from "lucide-react";

const projects = [
  { number: "01 / ACTIVE BUILD", title: "CrackSense", category: "Computer vision for automated infrastructure inspection.", description: "A semantic segmentation pipeline that pairs crack masks with geometry analysis, designed for eventual edge inference and drone-based inspection.", stack: ["SegFormer", "PyTorch", "OpenCV", "Edge AI"], active: true },
  { number: "02 / COMPUTER VISION", title: "Object Detection System", category: "Real-time detection, tracking and movement analysis.", description: "A multi-service CCTV intelligence pipeline for detection, tracking, people counting, line crossing and live streaming, orchestrated through a web dashboard.", stack: ["YOLOv8", "OpenCV", "Python", "FastAPI"], href: "https://github.com/ManasD2011/Object-Detection-Project" },
  { number: "03 / MEDICAL COMPUTER VISION", title: "Brain Tumor Detection", category: "MRI segmentation and tumour-mask visualization.", description: "A 2D U-Net segmentation workflow trained on BraTS 2021 MRI data, including preprocessing and a FastAPI endpoint for overlay outputs.", stack: ["U-Net", "TensorFlow", "NIfTI", "FastAPI"], href: "https://github.com/ManasD2011/Brain_Tumour_Detection" },
];

function ThemeToggle({ theme, setTheme }) { const next = theme === "light" ? "dark" : "light"; return <button className="theme-toggle" onClick={() => setTheme(next)} aria-label={`Switch to ${next} theme`} title={`Switch to ${next} theme`}>{theme === "light" ? <Moon size={15} /> : <Sun size={16} />}</button>; }

export default function App() {
  const [theme, setTheme] = useState(() => localStorage.getItem("theme") || "light");
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("theme", theme); }, [theme]);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { const cursor = document.querySelector(".custom-cursor"); const move = (event) => { cursor.style.transform = `translate(${event.clientX}px, ${event.clientY}px)`; }; window.addEventListener("pointermove", move); return () => window.removeEventListener("pointermove", move); }, []);
  const closeMenu = () => setMenuOpen(false);
  return <><span className="custom-cursor" aria-hidden="true" />
    <header className={`nav ${scrolled ? "nav-scrolled" : ""}`}><div className="container nav-inner"><a className="logo" href="#top" aria-label="Manas Deshpande home">M/</a><nav className={menuOpen ? "nav-links open" : "nav-links"} aria-label="Main navigation"><a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>About</a><a href={`${import.meta.env.BASE_URL}Manas_Deshpande_Resume.pdf`} target="_blank" rel="noreferrer">Resume <ArrowUpRight size={13} /></a></nav><div className="nav-actions"><ThemeToggle theme={theme} setTheme={setTheme} /><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></div></header>
    <main id="top">
      <section className="hero container"><div className="hero-main"><p className="eyebrow">MANAS DESHPANDE</p><h1>AI/ML<br />Engineer.</h1><p className="hero-copy">I build machine-learning systems from model development to deployment.</p><div className="hero-actions"><a className="button" href="#work">View work <ArrowDown size={15} /></a><a className="text-link" href="https://github.com/ManasD2011" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15} /></a></div></div><aside className="current"><p className="eyebrow">CURRENTLY BUILDING</p><h2>CrackSense</h2><p>Computer Vision<br />Edge AI</p><div className="status"><span /> Active development</div><a className="arrow-link" href="#cracksense">View progress <ArrowDown size={14} /></a></aside><a className="scroll-prompt" href="#work"><ArrowDown size={15} /> Scroll to explore</a></section>
      <section id="work" className="section container"><div className="section-intro"><p className="eyebrow">SELECTED WORK</p><h2>A selection of systems, experiments and products I’ve built.</h2></div><div className="project-list">{projects.map((project, index) => <article id={project.active ? "cracksense" : undefined} className="project" key={project.title}><p className="project-index">0{index + 1}</p><div className="project-copy"><p className="eyebrow">{project.number}</p><h3>{project.title}</h3></div><div className="project-detail"><p className="project-category">{project.category}</p><p className="project-description">{project.description}</p><div className="tag-list">{project.stack.map(item => <span key={item}>{item}</span>)}</div>{project.active ? <><p className="status"><span /> Active development</p><a className="arrow-link" href="#currently-building">View progress <ArrowDown size={14} /></a></> : <a className="arrow-link" href={project.href} target="_blank" rel="noreferrer">View project <ArrowUpRight size={14} /></a>}</div></article>)}</div></section>
      <section className="section container engineering"><div className="section-intro"><p className="eyebrow">ENGINEERING</p><h2>Tools and capabilities I use to take systems beyond a notebook.</h2></div><div className="capabilities">{[["Machine Learning", "PyTorch · Transformers · Computer Vision · Semantic Segmentation · Object Detection · NLP"], ["Backend", "Python · FastAPI · REST APIs · PostgreSQL"], ["Frontend", "React · TypeScript · Tailwind CSS"], ["Deployment", "Linux · Docker · Git · Raspberry Pi · Edge AI"]].map(([name, items], i) => <div className="capability" key={name}><span>0{i + 1}</span><h3>{name}</h3><p>{items}</p></div>)}</div></section>
      <section id="currently-building" className="section container active-section"><div><p className="eyebrow">CURRENTLY BUILDING</p><h2>CrackSense</h2><p>A computer-vision system for automated infrastructure crack inspection.</p></div><div className="stage-list"><p><Check size={15} /> Dataset preparation</p><p><Check size={15} /> Model development</p><p><Check size={15} /> Inference pipeline</p><p><Check size={15} /> Crack analysis</p><p className="next">→ Edge deployment</p><p className="planned">○ Drone validation</p></div></section>
      <section className="section container experience"><div className="section-intro"><p className="eyebrow">EXPERIENCE</p><h2>Learning through systems work.</h2></div><div className="timeline"><div><span>2026</span><h3>Trinetri Quantum</h3><p>Internship · Feb 2026 — Apr 2026</p></div><div><span>EDUCATION</span><h3>B.Tech, Electronics & Computer Science</h3><p>VIT Mumbai</p></div></div></section>
      <section id="about" className="section container about"><p className="eyebrow">ABOUT</p><div><h2>I’m Manas, an AI/ML engineer interested in practical machine-learning systems.</h2><p>My work sits at the intersection of machine learning, computer vision and software engineering. I enjoy building the inference pipeline, measuring it, optimizing it and putting it on real hardware.</p></div></section>
      <section id="contact" className="contact"><div className="container"><p className="eyebrow">CONTACT</p><h2>Let’s build something.</h2><p>I’m interested in opportunities involving machine learning, computer vision and backend systems.</p><div className="contact-links"><a href="mailto:manasdeshpande51@gmail.com">Email <ArrowUpRight size={15} /></a><a href="https://github.com/ManasD2011" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15} /></a><a href="https://linkedin.com/in/manas-deshpande21" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15} /></a><a href={`${import.meta.env.BASE_URL}Manas_Deshpande_Resume.pdf`} target="_blank" rel="noreferrer">Resume <ArrowUpRight size={15} /></a></div></div></section>
    </main><footer className="container footer"><span className="logo">M/</span><span>© 2026 Manas Deshpande</span><span>Built with React</span></footer>
  </>;
}
